name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and tag image
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo $COMMIT_SHA
          # build docker image
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-kubernetes-web:${COMMIT_SHA} .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to DockerHub
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo $COMMIT_SHA
          # push docker image
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-kubernetes-web:${COMMIT_SHA}
      
      - name: Trigger GitOps Workflow
        if: success()
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITOPS_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/mwinel/argocd-gitops-test/actions/workflows/image-updater.yaml/dispatches \
            -d '{"ref":"main"}'
